config/routes.rb
Rails.application.routes.draw do
  resources :dinosaurs

end

app/models/dinosaur.rb
class Dinosaur < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController
  # respond_to :json ,:html
  # This controller just respond to Jason.
  def index
  	@dinosaurs = Dinosaur.all
  	# render :json => @dinosaurs
 	# respond_with @dinosaurs
  end

  def show
  	@dinosaur = Dinosaur.find(params[:id])
  	render :json => @dinosaur
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/views/dinosaurs/index.html.erb
<h1>Dinosaurs!</h1>
<ul id="dinosaur-list">
	<% @dinosaurs.each do |dino| %>					
		<li><%= link_to dino.name, dinosaur_path(dino), :class => "dino-link" %></li> 
	<% end %>
</ul>

 <div id= "dinosaur-details">

 </div>

 <script id="dino" type="text/html">
 	<ul>
		<li>Name:{{name}}</li> 
		<li>Size:{{sizing}}</li> 
		<li>Wings:{{wings}} </li> 
		<li>Vegetarian? {{vegetarian}} %></li> 
	<ul>

 </script>

app/views/dinosaurs/show.html.erb
<h1>Dinosaurs#show</h1>
<p>Find me in app/views/dinosaurs/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JasonVer1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>